blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/jaconi-io/morp/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerabilities
    url: "mailto:security@jaconi.io"
    about: Please report security vulnerabilities here.