name: Feature Request
description: Request new functionality
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please answer the following questions for yourself before submitting an issue.
      options:
        - label: I am running the most recent stable version.
          required: true
        - label: I checked the documentation and found no answer.
          required: true
        - label: I checked to make sure that this feature request has not already been filed.
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Please describe the problem you are trying to solve.
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired Solution
      description: Please describe the solution you would like to see implemented.
      placeholder: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Please describe alternatives you have already considered.
      placeholder: |
        1. Alternative solution 1
        2. Workaround 2
        3. you get it...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any additional relevant information.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jaconi-io/morp/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
