# keycloak is running on 8080 so we need different ports for Morp here
server:
  port: 8081
management:
  server:
    port: 8082

# Routing config
spring:
  cloud:
    gateway:
      routes:
        - id: upstream-tenant-path
          uri: http://upstream:1080
          predicates:
            - Host=morp:8081
            - Path=/upstream/{tenant}/{path}
          filters:
            - SetPath=/{path}
            - SetRequestHeader=x-tenant-id, {tenant}
        - id: upstream-tenant-host
          uri: http://upstream:1080
          predicates:
            - Host={tenant}-morp:8081
            - Path=/upstream/{path}
          filters:
            - SetPath=/{path}
            - SetRequestHeader=x-tenant-id, {tenant}

morp:
  default-oauth2-client-registration: keycloak
  # Tenant identification
  tenant-extractors:
    - host-pattern:
        pattern: (\w+)-morp
        capture-group: 1
    - path-pattern:
        pattern: /upstream/(\w+)/.*
        capture-group: 1

  tenant:
    tenant1:
      # Configure tenant-specific credentials here.
      registration:
        client-id: morp
        client-secret: secret

  oauth2-client:
    registration:
      keycloak:
        client-id: morp
        client-secret: secret
        scope:
          - openid
          - profile
          - email
    provider:
      keycloak:
        issuer-uri: http://keycloak:8080/realms/{tenant}

logging.level:
  root: DEBUG
  reactor.core: ERROR
  io.netty: ERROR
