version: "3.4"
services:

  # Run a vanilla Keycloak with some test realms
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
    - start
    - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
    ports:
      - "9000:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/realms/tenant1/.well-known/openid-configuration",
        ]

  # use httpbin as OAuth2 protected backend (so we can easily inspect the results of the OAuth2 dance)
  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
      - 80
