spring:
  cloud:
    gateway:
      routes:
        - id: httpbin
          uri: http://httpbin
          predicates:
            - Host={tenant}.localtest.me:8080

# for convenience read a git-ignored properties file holding credentials
spring.config.import: optional:file:./config/secret.properties

morp:
  default-oauth2-client-registration: keycloak

  tenant:
    foo:
      registration:
        client-secret: secret
    bar:
      registration:
        client-secret: another-secret

  oauth2-client:
    registration:
      keycloak:
        client-id: morp
        scope:
          - openid
          - profile
          - email
    provider:
      keycloak:
        issuer-uri: http://keycloak.localtest.me:9000/realms/{tenant}
