name: Generate and push documentation

on:
  release:
    types:
      - published

jobs:
  build_docs:
    name: Generate and push documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits/branches

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: mkdocs/requirements.txt

      - name: Install Python dependencies
        run: python3 -m pip install -r ./mkdocs/requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy with mike 🚀
        run: |
          cd mkdocs
          mike deploy --update-aliases ${{ github.event.release.tag_name }} latest
          mike set-default --push latest
