name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.JACONI_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@a009669cd5ded58aeceb80a10a7b8697138f01d0

      - uses: docker/setup-qemu-action@e77e8065d9f7ec6abdd9838668cd7b43924dd64d
      - uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a
      - uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.JACONI_BOT_GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.JACONI_BOT_USERNAME }}
        run: |
          yarn add semantic-release
          yarn add @semantic-release/exec
          yarn add @semantic-release/git
          yarn add @semantic-release/github
          yarn add @semantic-release/release-notes-generator
          yarn add @semantic-release/changelog
          yarn run semantic-release
