version: "3.9"
services:

  mkdocs:
    image: python:3.10-alpine
    command: >
      sh -c "cd /workspace &&
             pip install -r requirements.txt &&
             mkdocs serve -a 0.0.0.0:8000"
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"